default:
    image: node:20-alpine3.17
       

stages:
    - deploy

deploy-job:
    stage: deploy        
    before_script:
        - npm install 
        - echo "Install packages"

        # - npm run lint:fix
        # - echo "Lint checking complete"

        # - npm run format
        # - echo "Code format checking complete."

        - CI= npm run build
        - echo "Build generated!"

    script:
        - echo "Good to deploy"

       
    artifacts:
        paths:
            - public

# Setup GitLab runner For reference:    https://docs.gitlab.com/runner/install/linux-repository.html
# Run job :                             gitlab-Runner exec shell deploy-job
