default:
    image: node:20-alpine3.17
       

stages:
    - deploy

deploy-job:
    stage: deploy        
    
    # variables:
    #     BUILD_PATH: 
    #     DEPLOY_PATH:
    #     SSH_PRIVATE_KEY:
    #     SSH_USER:
    #     VM_IPADDRESS:
    #     SSH_REPOSITORY_URL: 

    before_script:
        - echo "Setup SSH"
        - 'command -v ssh-agent >/dev/null || ( apk add --update openssh )' 
        - eval $(ssh-agent -s)
        - echo "${SSH_PRIVATE_KEY}" | ssh-add 
        - mkdir -p ~/.ssh
        - chmod 0700 ~/.ssh
        - ssh-keyscan $VM_IPADDRESS >> ~/.ssh/known_hosts
        - chmod 0700 ~/.ssh/known_hosts

    script:
        - ssh $SSH_USER@$VM_IPADDRESS "rm -rf $BUILD_PATH/* && 
            cd $BUILD_PATH && 
            git clone $SSH_REPOSITORY_URL && 
            cd optimization-app-ui && 
            npm i && npm run build && 
            sudo rm -rf $DEPLOY_PATH/* && 
            sudo mv -vuf build/* $DEPLOY_PATH"
       
    artifacts:
        paths:
            - public

# Setup GitLab runner For reference:    https://docs.gitlab.com/runner/install/linux-repository.html
# Run job :                             gitlab-Runner exec shell deploy-job
